name: Publish textarena

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      -
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        name: Use Node.js 14.17.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
          cache: 'yarn'
      -
        name: Install
        run: yarn
      -
        name: Build
        run: yarn build
      -
        name: Run linter
        run: yarn lint
      -
        name: Run tests
        run: yarn test:jest
      -
        name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      -
        name: Deploy to GitHub Pages
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
